- name: check mount
  become: true
  become_user: root
  shell: df -h | grep mnt/solana-ledger
  ignore_errors: true
  register: mount_mnt

- name: Get list of NVMe drives over 750GB that are not mounted
  become: true
  become_user: root
  shell: >
    lsblk -ln -o NAME,SIZE -d -b | grep nvme | awk '$2 > 750*1024*1024*1024 {print $1}' | 
    while read drive; do
      if ! grep -qs "/dev/$drive " /proc/mounts; then
        echo $drive
        break
      fi
    done
  register: ledger_disk_raw
  when: mount_mnt.rc != 0

- name: Set ledger_disk variable
  set_fact:
    ledger_disk: "{{ ledger_disk_raw.stdout }}"
  when: mount_mnt.rc != 0

- name: Format disks with ext4
  become: true
  become_user: root
  shell: mkfs.ext4 /dev/{{ ledger_disk }}
  when: mount_mnt.rc != 0

- name: Mount disks for ledger
  become: true
  become_user: root
  shell: mount /dev/{{ ledger_disk }} /mnt/solana-ledger && chown -R solana:solana /mnt/solana-ledger
  when: mount_mnt.rc != 0

- name: Add mounted disk to fstab
  become: true
  become_user: root
  lineinfile:
    dest: /etc/fstab
    state: present
    line: "/dev/{{ ledger_disk }}    /mnt/solana-ledger    ext4    defaults    0    1"
  when: mount_mnt.rc != 0