- name: Create swap file
  become: true
  become_user: root
  command:
    dd if=/dev/zero of=/mnt/solana-accounts/swapfile bs=1024 count={{ swap_mb }}k
    creates="/mnt/solana-accounts/swapfile"

- name: Change swap file permissions
  become: true
  become_user: root
  file: 
    path=/mnt/solana-accounts/swapfile
    owner=root
    group=root
    mode=0600

- name: Check swap file type
  become: true
  become_user: root
  command: file /mnt/solana-accounts/swapfile
  register: swapfile

- name: Make swap file
  become: true
  become_user: root
  command: "sudo mkswap /mnt/solana-accounts/swapfile"
  when: swapfile.stdout.find('swap file') == -1

- name: Write swap entry in fstab
  become: true
  become_user: root
  mount: name=none
    src=/mnt/solana-accounts/swapfile
    fstype=swap
    opts=sw
    passno=0
    dump=0
    state=present

- name: swap check
  become: true
  become_user: root
  ignore_errors: yes
  shell: swapon -show | grep /mnt/solana-accounts/swapfile
  register: swap_check

- name: Mount swap
  become: true
  become_user: root
  command: "swapon /mnt/solana-accounts/swapfile"
  when: swap_check.rc != 0